import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Tix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`grid min-h-svh grid-rows-[auto_1fr_auto] antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
